makePDF.py
As discussed, with you in #88. 
Let me know if you need adjustements.
Here is an example of the required settings for this to work.
"builder_settings" : {
"windows" : {
// Additional environment variables (eg. TEXINPUTS BIBINPUTS)
"env" : {
"TEXINPUTS": "Q:/@Administration/@Include;Q:/@Documents/@Include;.",
"BIBINPUTS": "Q:/@Documents/@Bibs"
}
}
}
=> Handle custom env variables (specified in builder_settings.platform)

jumpToPDF.py
From [README.markdown](https://github.com/SublimeText/LaTeXTools/blob/master/README.markdown)
> If you have installed Skim in a non-standard location, there is not much you can do short of hacking the `jumpToPDF.py` file (**not supported!**). This will change in the near future. 
I couldn't wait for it, so I did it myself. Let me know if it looks good!
=> Make from_keybinding default to false; Find Skim if not located at default path

figure.sublime-snippet, table.sublime-snippet
\begin{center}...\end{center} includes additional vertical space and thus
should be avoided in float environments.
See section 3.1 in:
"An essential guide to LATEX 2ε usage - Obsolete commands and packages"
ftp://ftp.dante.de/tex-archive/info/l2tabu/english/l2tabuen.pdf
=> Replaced \begin{center}[...] with \centering in snippets table and figure

delete_temp_files.py
I don't know if it's very common, but in long manuscripts, like a thesis for example, I often split up the chapters in separated files and even in separated folders. It causes the compiler to scatter the temporary files through the created folders. So I modified `delete_temp_files.py` to delete the temporary files recursively.
=> Delete temporary files recursively

Default (Linux).sublime-keymap, Default (OSX).sublime-keymap, Default (Windows).sublime-keymap
It works with Vintage and without Vintage (didn't try Vintageous).
=> Fix '$' auto-pairing and Vintage (closes #308)

kpsewhich.py, latex_cite_completions.py
Finding bib files in the TEXMF tree seems to come up frequently---e.g. #314, #60 and #258. This seemed like a simple, clean way of implementing it: just execute `kpsewhich` with a file name and let it do the search. In the interest of performance and minimising damage to already existing projects, I've set it so that `kpsewhich` only gets run if LaTeXTools cannot otherwise find a specified bib file. If `kpsewhich` cannot be found on the path, it fails silently. I've tested this successfully on both ST2 and ST3.
=> Bibfiles in TEXMF Tree

builders/traditionalBuilder.py
Bugfix for https://github.com/SublimeText/LaTeXTools/issues/589. Only changes the indentation in one line from spaces to tabs to be consistent for the whole file.
=> Bugfix for 589 (inconsistent indentation )

latex_cite_completions.py
Simple implementation of the feature requested in #518. When entering a cite command with only one entry in the bibliography, that entry will automatically be filled in.
=> Citing from a bibliography with one entry

parseTeXlog.py
The root cause of #477 is not properly handling pdfTeX warnings with the message `destination with the same identifier... has been already used, duplicate ignored` when they appear in the odd configuration of that log. These are primarily noise or can be addressed by [ensuring `hyperref` is loaded after most other packages](http://www.tex.ac.uk/FAQ-hyperdupdest.html).
This change will add these warnings to the list of warnings if they are not otherwise handled. It shouldn't break anything, but LaTeX log files are a mess...
=> Fix for parse log with duplicate identifier messages

Default (Linux).sublime-keymap, Default (OSX).sublime-keymap, Default (Windows).sublime-keymap
While looking at support apacite's cite commands, which use angle brackets, I discovered that the keymap rule intended for Beamer overlays wasn't configured properly. For example, if you create a document that invokes `\textbf{}`, any time you enter an angle bracket after that you will get `<+->` regardless of the context, e.g.,
\textbf{this is important}. But however <+->
This commit fixes this so it will work as intended, i.e., for a small list of commands, pressing `<` will insert the beamer overlay snippet.
=> Fix Beamer angle bracket snippet

LaTeXTools.default-settings, README.markdown, jumpToPDF.py
This is an adaptation and generalisation of @r-stein's suggestion from #495. Basically if `keep_focus` is set on Windows or Linux, it runs either `sublime_text` or `subl` to regain focus after a (configurable) short delay.
I've added some code to work out where the appropriate executable is, though it should be auto-detected on *most* configurations. The only worrying setup is ST2 where `subl` is not available on the `PATH`, in which, case the platform-specific `sublime_executable` setting must be set appropriately. Alternatively, the `sublime_executable` setting can be set and the auto-detect code will not be run.
=> Keep focus for Windows and Linux

jumpto_tex_file.py
This fixes https://github.com/SublimeText/LaTeXTools/issues/624. It just removes the shell argument in the `subprocess.Popen`-command for opening image files, because it seems not to be necessary and produces errors on linux.
*(I added this argument before splitting the argument string into an argument array.)*
=> Bugfix: Remove subprocess.Popen shell-argument in the "jump to image file" command

LaTeXTools.default-settings
The settings  "tex_file_exts" and "latextools_set_syntax" are listed twice in the main settings file (LaTeXTools.default-settings).
=> Delete duplicate lines in default-settings.

builders/scriptBuilder.py
This pull request adds an actual functioning script builder, at least as far as I understand the intention of it. It is able to run simple lists of commands, configurable in the `LaTeXTools.sublime-settings` file or even launching external build tools. There's some fairly extensive docs added to the README on how to configure it, etc., and some warnings on the assumptions that LaTeXTools makes.
The builder works by constructing and yielding `Popen()` objects to the `make_pdf` command, which has been modified to accept `Popen` objects *in addition to* strings or lists.
=> Script Builder

Default (Linux).sublime-keymap, Default (OSX).sublime-keymap, Default (Windows).sublime-keymap, LaTeXTools.default-settings, latexFillAll.py, latex_cwl_completions.py, latex_env_completions.py, latex_input_completions.py
Changes the cwl completion inside the `\begin` and `\end` command to provide the environment names.
Integrates into fill-all helper:
Technical detail:
The environment names are extracted from the `\end{env}` lines in the cwl file, because this directly generates a list without duplicates. This should be adequate, because every environment needs the `\end`-command.
*Edit:*
Added Fill-All Helper
=> CWL completion for environment names

builders/pdfBuilder.py, builders/scriptBuilder.py, builders/simpleBuilder.py, builders/traditionalBuilder.py, getTeXRoot.py, latextools_utils/__init__.py, latextools_utils/tex_directives.py, makePDF.py
Some back-end changes that do two things:
1) It moves all the parsing code for `%!TEX` directives to a single place
2) It extracts the code for determining the `engine` and `options` settings used by the traditional builder and makes them available to all builders
=> Common `%!TEX` directive parsing

README.markdown, getTeXRoot.py, latextools_utils/__init__.py, latextools_utils/sublime.py
This is identical in intention to #485, though the implementation is quite different. As such it should resolve #152.
The upshot of the change is that when the `TEXroot` setting is a relative path, it will be resolved relative to the location of the project file (which I think is the expected behaviour). This is necessary to support relative TEXroot paths with included documents in subfolders.
There are three other noteworthy changes, to how `getTeXRoot` works after this PR, though this shouldn't affect any documented behaviour:
1. I've changed the order of precedence of the preference setting versus the text in the file itself. Previously, a `TEXroot` setting would override the `%!TEX root` magic comment. With this PR, the magic comment will override the `TEXroot` setting.
1. Instead of …
=> Support TEXroot relative to project file

latex_cite_completions.py
I usually write my texts using the same set of .bib files; I have several of these, separated by subject, in one directory. When using several .bib files in the ```\bibliography``` command, I find it much more readable to have each file in one line, as opposed to one big line. This is an example:
```
\bibliography{%
IEEEfull,%
../bib/support,%
../bib/simulation,%
../bib/sdfg_tools_and_methods,%
(...)
../bib/optimization%
}
```
LaTeX has no problem with this, but LaTeXTools will fail to open the .bib files, as it thinks the whitespaces (including ```\n```s) are a part of the filenames. This is a quick one-liner to ignore trailing whitespaces on the filenames. If perhaps this is not the best way to do this, I am open to suggestions.
=> Support for multi-line/spaces in \bibliography command.

texSyntaxListener.py
This PR changes the syntax listener to
- support of the new ST3 `*.sublime-syntax` files
- use `score_selector` to detect whether any tex syntax is set. This is more resistant to user self-defined syntax files, but also to special syntax support like Beamer or TikZ.
this has been mentioned by @keith-hall in https://github.com/SublimeText/LaTeXTools/commit/1baf0efd52dc2dee30c17eb6b99120f2fdb88abe#commitcomment-17285547
=> Improved TeXSyntaxListener for ST3 and user defined syntax

latex_cite_completions.py
This slightly increases the robustness and readability of author parsing in cite completions.
Before this PR a bug occured if an author is empty `A and  and C`, because of the check `a[-1] != '}'`. The fix is just filter out empty strings via `if len(a) > 0`.
=> Improved robustness of author parsing for cite completion

latex_ref_completions.py
This is similar to the behaviour implemented in #571, but for `\ref` rather than `\cite`.
=> Autocomplete label if there is only one

latex_env_completions.py, latex_input_completions.py, latex_ref_cite_completions.py
This fixes https://github.com/SublimeText/LaTeXTools/issues/691
The same behavior occurs for "environment", "input", "ref " and "cite" completions. This fixes env and input completions and partially ref and cite (not complete because I was worried breaking something with the `pre_snippet` stuff).
=> Multiple-cursor support for FillAll helper

LaTeXTools.sublime-settings, viewers/okular_viewer.py
Partial solution to #730. See [here](https://github.com/SublimeText/LaTeXTools/issues/730#issuecomment-219309706) for limitations.
Essentially, to launch Okular, we first check if an instance with `--unique` is already running. If it is, we proceed as normal. If it isn't, we run `okular --unique` and then proceed with the normal sequence. This ensures that the document is *always* opened by the "unique" instance of Okular.
=> Ensure Okular is always launched in a unique instance

Default (Linux).sublime-keymap, Default (OSX).sublime-keymap, Default (Windows).sublime-keymap, Insert environment.sublime-snippet, latexCommand.py, latexEnvironment.py
Using the keybinding `C-l,C-n` this PR inserts an environment snippet, which ends inside the environment. Before the "wrap environment" snippet has been inserted, which ended behind the environment. The old behavior remains if text is selected.
I also changed the behavior of `C-l, e` and `C-l, c` if they are not prefixed by a word to let the user input the environment/command.
| | before | after this PR |
|---|----|---|
| `C-l,C-n` | ![lt_insert_env_old](https://cloud.githubusercontent.com/assets/12573621/15349558/02ae1796-1cd4-11e6-8a3a-51d8648ee734.gif) | ![lt_insert_env_new](https://cloud.githubusercontent.com/assets/12573621/15349515/b8ea322a-1cd3-11e6-9ad3-956eee667fea.gif) |
| `C-l, e` | ![lt_env_old](https://cloud.githubusercontent.com/assets/12573621/15355969/3016d1f6-1cf6-11e6-9d0 …
=> Improved insert environment behavior

00_reload_submodules.py, 01_temp_file_cleanup.py, LaTeXTools.sublime-settings, README.markdown, builders/basicBuilder.py, builders/pdfBuilder.py, builders/scriptBuilder.py, builders/simpleBuilder.py, builders/traditionalBuilder.py, delete_temp_files.py, getTeXRoot.py, jumpToPDF.py, latexDocumentationViewer.py, latex_input_completions.py, latextools_utils/__init__.py, latextools_utils/distro_utils.py, latextools_utils/output_directory.py, latextools_utils/tex_directives.py, makePDF.py
This adds the much-requested ability to use `--output-directory` and `--aux-directory` (cf. #559, #98, #161, #163, #383, #169). I've also added support for `--jobname`, as it pretty much has the same requirements and touches the same parts of the code.
All are controlled through either a setting or (yet another) `%!TEX` directive. The setting and directive name are `output_directory`, `aux_directory`, and `jobname` respectively. In addition, these changes will pick up any `--aux-directory=...`, `--output-directory=...`, or `--jobname=...` flags set via the TeX options support.
`output_directory` and `aux_directory` can be set to any of the following values:
* a path (relative to the main tex file, absolute, or, if specified in a project file, relative to the project file)
* `<<temp>>` a …
=> Add support for --output-directory, --aux-directory, and --jobname

LaTeX math.sublime-completions
If use the original one, `\` shall disappear after toggling.
=> fix trigger toggle for \epsilon and \varepsilon

external/bibtex/lexer.py, external/bibtex/parser.py, external/bibtex/tests/lexer_tests.py, external/bibtex/tests/parser_tests.py
* Eliminates wrong-headed support for \" escapes in quoted strings
* Adds support for brackets in quoted strings
* Removes special case for @string values
=> Update bibtex parser to support cryptobib

LaTeXTools Console.hidden-tmLanguage, makePDF.py
Adds some colour to errors, warnings and bad boxes in the build console, making them stand out a bit more.
=> Highlight errors, warnings and bad boxes in the console

LaTeXTools.sublime-settings, README.markdown, makePDF.py
This feature is occasionally requested (e.g. #463, #668) and, more broadly, I can see the need for something like this in certain circumstances, e.g., if you don't care about moving to a particular position in the PDF and your viewer already supports automatic updates when the PDF file is changed. Plus, the implementation is very simple.
=> Add a setting to control whether or not to launch PDF viewer on build

LaTeXTools (Advanced).sublime-settings, latex_cite_completions.py, latex_ref_completions.py
This improves the support for package subfile as requested in https://github.com/SublimeText/LaTeXTools/issues/670
It does not add a full support for the package, but improves it. It does
- add fillall helper if you type `\subfile{`
- adds labels defined in subfiles
- adds bibfiles from subfiles
=> Improve `subfile` support

01_reload_submodules.py, latextools_utils/quickpanel.py
This PR adds a utility function, which creates a quickpanel to navigate between file regions. It has a pretty simple interface and can be used with the analysis results.
I am looking forward for the following features:
*Full document "goto overlay":*
*Show label usage in "jump to anywhere":*
*Search for commands in document:*
@msiniscalchi @ig0774  I licensed this file with the MIT license, because I think it is also useful in other projects and MIT seems to be the most permissive license.
If you also don't see a problem with the license I would merge this, such that I can create follow up PRs.
=> Utility function: Quickpanel for file navigation

01_reload_submodules.py, bibliography_plugins/newBibliography.py, bibliography_plugins/traditionalBibliography.py, latex_cite_completions.py, latextools_utils/bibcache.py, latextools_utils/bibformat.py, latextools_utils/cache.py
This has been discussed in https://github.com/SublimeText/LaTeXTools/pull/759.
This PR adds a special caching behavior, which improves the performance of cite completions.
Two modules are added:
- `bibformat`: Utility module for formating cite completion strings
- `bibcache`: The core of this PR. A special cache for bib files.
Before caching the `bibcache` module calculates the formating strings for the cite panel and the cite autocompletion.
These results are stored in a new dict under the keys `<panel_formatted>` and `<autocomplete_formatted>`. In addition this dict keeps important keys and will be cached and given to the completion.
The completion will be check and use the preformatted entry, if a special key is present. Otherwise it will work as before. Hence it is fully backward …
=> Caching for BibTeX cite completions

README.markdown, jumpto_anywhere.py
Redux of #761, but using `jumpto_anywhere` and with no fancy processing. Obviously only workable if the file has been saved to disk.
=> Add ability to jump to the root from magic comment

delete_temp_files.py, jumpToPDF.py, toggle_show.py
This change the visibility of the commands for the command panel `C-Shift-p`. The commands will be invisible if you are not in a LaTeX file.
Currently I just made the command invisible, which are not applicable outside LaTeX files. Remaining command visible should be discussed:
- Reset user settings to default
- Create mousemap in user folder
- Build cache of LaTeX packages
- View package documentation
~~I would at least make the documentation command invisible.~~
=> Hide commands if not in LaTeX files

Default (Linux).sublime-mousemap, Default (OSX).sublime-mousemap, Default (Windows).sublime-mousemap, README.markdown, create_mousemap.py, jumpto_anywhere.py, jumpto_tex_file.py
This fixes #784 and #786.
It uses unique keybindings and adapts them if SublimeCodeIntel is installed to be compatible.
=> Unique jump-to-anywhere mouse bindings

README.markdown, latex_cwl_completions.py, latex_env_completions.py, latextools_utils/analysis.py
This is a pretty drastic overhaul of the cwl code to support loading completions based on the packages used in the current document. I think this is a nice-to-have feature, since it requires the user to mess around less with the settings. This behaviour can be *disabled* by setting the `cwl_autoload` setting to `False`.
The packages are parsed from the main file, using the analysis tools. and *added* to the list in the existing `cwl_list` setting. This is because certain default files (`tex.cwl`, `latex-209.cwl`, `latex-document.cwl`) which should probably be loaded are otherwise missed.
The other key difference is that we now only parse the cwl files once and store the results of that for future use. This is done in a background thread when the plugin was loaded. This is done to keep the …
=> Use packages to determine which cwl files to use

latex_cwl_completions.py, latex_env_completions.py, latex_own_command_completions.py
This PR adds completions for self-defined commands and environments.
The completions are added into the cwl completions and are only available if cwl completions are available.
Supported completions:
- environment in `\(re)newenvironment`
- commands in `\(re)newcommand`
- math operators from `\DeclareMathOperator` (only inside math)
Feel free to suggest more.
=> Self-defined commands completions

jumpToPDF.py, latex_input_completions.py, latextools_utils/output_directory.py
This adds support for symlinks requested in #792 and #796, as well as some unreported issues with `output_directory`.
There are still likely still some cases where symlinks will cause possibly unexpected behaviour. Two I'm aware of:
1. Compiling from a document that uses a symlink to point to the root will have a different "Compiling..." message than compiling from the root directly. I don't think this really causes problems.
1. Using the `jump_to_anywhere` functions on a file opened via symlinks with a copy opened from the real path results in multiple tabs of the same file that don't share the same buffer. This is addressable, but doing so would unnecessarily slow things down in cases where the file is only ever opened via a symlink or where symlinks aren't involved at all, as we'd have …
=> Improve support for symlinks

Default (Linux).sublime-keymap, Default (OSX).sublime-keymap, Default (Windows).sublime-keymap, LaTeXTools.sublime-settings, README.markdown, latextools_utils/progress_indicator.py, makePDF.py
This builds on #712 and is intended to run builds in a less obtrusive way. Among other things, it implements #638 while addressing [my concerns here](https://github.com/SublimeText/LaTeXTools/pull/638#issuecomment-169167969).
This (if it is merged) is a rather major change, so I'm attempting to solicit some feedback.
1. By default, the output panel is not displayed initially unless `hide_build_panel` is set to `never`. Instead, an indicator (borrowed from [PackageControl](https://packagecontrol.io/)) is used to indicate the build is in progress.
1. By default, the output panel appears if any errors or warnings occur including (and this is the crucial bit) any exceptions thrown at the various points we already have "COULD NOT COMPILE" messages. If `hide_build_panel` is set to `always`, of …
=> Less Obtrusive Build Panel

Default (Linux).sublime-keymap, Default (OSX).sublime-keymap, Default (Windows).sublime-keymap, LaTeXTools (Advanced).sublime-settings, LaTeXTools.sublime-settings, toc_quickpanel.py
This adds a whole document "table of content" overlay to replace the default `C-r` keybinding (opt-out). It is also accessible via `C-l, C-r`.
The entries are indented (chapter<section<subsection<...) to create a better overview and you can show and hide the labels.
TODO:
=> ToC section quickpanel

LaTeXTools.sublime-settings, README.markdown, makePDF.py
ST adds phantom to indicate build errors in build 3118. This PR adds similar phantoms to the LaTeX build. *This is necessary, because it does not use the `exec` command.*
It looks like:
It might be necessary to change the OSX and Linux regex, because they only match the message up to the first dot. I.e.:
- OSX: `^(...*?):([0-9]+): ([0-9]*)([^\\.]+)` to `^(...*?):([0-9]+): ([0-9]*)(.*)$`
- Linux: `^(...*?):([0-9]+): ([0-9]*)([^\\.]+)` to `^(...*?):([0-9]+): ([0-9]*)(.*)$`
=> Phantoms for build errors

builders/basicBuilder.py, builders/pdfBuilder.py, builders/scriptBuilder.py
This implements option 2 outlined [in this comment on #813](https://github.com/SublimeText/LaTeXTools/issues/813#issuecomment-239665358). Essentially, if the `output_directory` and / or `aux_directory` point to a path that is a subfolder of the path containing the main file, we use a relative path for `output_directory` and `aux_directory` instead of an absolute path.
The underlying issue in #813 is a mismatch between the font encoding pdfLaTeX uses to represent в and в as its defined in UTF-8. This doesn't do anything to resolve that issue. However, as long as `output_directory` and `aux_directory` are specified relative to the main file and the file part only contains ASCII characters, the issue should be avoidable. Alternatively, using XeTeX or LuaTeX (which internally use UTF-8) also …
=> Pass out and aux dir as relative paths to LaTeX if possible

latex_fill_all.py
Mostly this is aimed at addressing the concerns raised in #827 and, I think, overall makes the fill all stuff a bit more intuitive.
Changes:
1) Full stops, parentheses and a range of other characters will no longer be gobbled.
2) The fill all command no longer gobbles *anything* if being entered via one of the auto-triggers (`{`, `[`, `,`)
3) The `smart_bracket_auto_trigger` now works closer to how it was intended.
=> Latex fill all improvements

Default (Linux).sublime-keymap, Default (OSX).sublime-keymap, Default (Windows).sublime-keymap, LaTeXTools.sublime-settings, latex_directive_completions.py, latex_fill_all.py, latextools_utils/internal_types.py, toggle_show.py
This add the `!TEX` directives to the fill all helper, supported directives are:
- `program` show the programs `pdflatex`, `xelatex`, `lualatex` and also `pdftex`, `xetex`, `luatex`
- `root` seach current folder and parent folders for tex files
- `spellcheck` show the supported locales
Each entry is added in the auto completion menu, if you write `% !TEX`. In addition it adds a trigger on `=`.
@ig0774 This still requires minor changes in the fill all helper, because it blacklist comment scopes. It might be good to add a method `get_supported_scopes`, which returns the scopes and is `-comment` by default.
=> Add !TEX directives to the fill all helper

viewers/sumatra_viewer.py
Loads the path to Sumatra from the `App Paths` key, which is used by the Windows shell to locate executables, e.g., when double-clicking on a PDF document.
This should get us closer to working out of the box if Sumatra was installed in a non-standard location.
=> Load Sumatra location from registry

Default (Linux).sublime-keymap, Default (OSX).sublime-keymap, Default (Windows).sublime-keymap, LaTeX.sublime-build, README.markdown, builders/traditionalBuilder.py, latextools_sublime_version_listener.py, latextools_utils/sublime_utils.py, makePDF.py
This adds a few build variants for some simple configurations and, more importantly, adds a way for custom `.sublime-build` files to override build settings.
Basically, this allows us to implement something not far off what was requested in #255:
This menu can be brought up by pressing `C-shift-b`. On ST3, after build 3080, this is, of course, simply the default behaviour. However, I've back-ported something similar for earlier versions of ST3 and for ST2. The chosen build variant will persist across builds, but can be reset by choosing the **LaTeX** variant, which is simply the default configuration. (The functionality isn't *exactly* the same, but it's quite close; the main difference is that the selected build is *not* saved across windows or persisted after the application closes). …
=> Add variants for different build configurations

Default (Linux).sublime-keymap, Default (OSX).sublime-keymap, Default (Windows).sublime-keymap
This fixes https://github.com/SublimeText/LaTeXTools/issues/857 and does several improvements for inserting $ pairs including better compatibility for the new LaTeX Syntax.
=> Improved keybinding for inserting $ pairs

latex_cwl_completions.py, latextools_utils/parser_utils.py
This PR extends CWL-completions to insert the matching `\end{}` tag when a `\begin{}` tag is inserted. In addition, where in the CWL files it indicates that a completion uses `\item`, this will automatically insert a blank `\item`. E.g.,
`\begin{}` expands to:
```latex
\begin{|}
\end{|}
```
(where `|` indicates the cursor)
`\begin{align}` expands to:
```latex
\begin{align}
|
\end{align}
```
`\begin{enumerate}` expands to:
```latex
\begin{enumerate}
\item |
\end{enumerate}
```
Additionally, I've forced the CWL-autocompletion box to be more or less the same size regardless of the completions shown, which hopefully helps with the visibility of some completions.
=> CWL-completions for \begin{}...\end{}

dependencies.json
This PR adds the [markdown-popups](http://facelessuser.github.io/sublime-markdown-popups/usage/#dependencies) as a [dependency](https://packagecontrol.io/docs/dependencies). This is a popular library to provide functions for popups and phantoms. Since these are used by upcoming PRs (https://github.com/SublimeText/LaTeXTools/pull/785), we should ensure that the dependency is installed.
=> Dependency for `markdown-popups`

system_check.py
- The System Check now accepts alternative program names and is successful if any of them is present
- Now GhostScript is found on Windows if either gswin32c or gswin64c or gs is installed.
This was suggested by @Gormador in #891.
=> Improved System Check detection of Ghostscript on Windows

builders/scriptBuilder.py, latextools_utils/external_command.py
On Windows, shell=True supports arguments passed as a list, but not so on Linux and OS X, which has to due with the semantics of the underlying calls.
This should fix #894.
TODO:
=> "Properly" handle the shell=... depending on OS, etc.

builders/scriptBuilder.py, latextools_utils/external_command.py, viewers/sumatra_viewer.py
This builds off of #898 and fixes #900.
The problem is that Sumatra actually *was* being launched, but as a hidden window. This fix may require killing a running Sumatra process via the Task Manager.
=> Make Sumatra visible on Windows

LaTeXTools (Advanced).sublime-settings, LaTeXTools.sublime-settings, st_preview/preview_math.py
Now the foreground color is set inside the tex file instead of while converting the pdf to png.
This essentially does what @musm and @ig0774  have suggested in #901.
=> Preview: Move the color from ImageMagick to the tex file

st_preview/preview_image.py, st_preview/preview_math.py
Add error information in the the phantom/popup, if the generation of the preview image fails.
- The user now knows whether it fails or just takes a long time
- The step where it fails "creating pdf"/"converting pdf to png" is added to improve the debugging
- I creates an error file. We may append further error informations to that file to improve the debugging process further.
=> Preview: Improve the feedback if previewing fails 

st_preview/preview_utils.py, system_check.py
This adds a caching for the result of the `_get_convert_command`.
- it does not change, except from the edge case of installing ImageMagick while running ST (just restart ST)
- I assumed `convert_installed` to be constant time (it takes 0.05 - 0.2 s on my machine w/o caching)
=> Cache the result of `_get_convert_command`

st_preview/preview_math.py
Help people with debugging math-live preview by access to more information
- Add more information to the error report file, this is
+ the original tex file
+ the parsed log file (errors + warnings)
+ the raw log file
- Add a button to run the system check or show the error report file to the math phantoms (if the build fails)
=> Preview: Improve error reports

README.markdown, system_check.hidden-tmLanguage, system_check.py, system_check.sublime-syntax
Checks for the existence of packages explicitly used by the equation preview. Note that this doesn't check the availability of the dependencies of the used packages. This is intended to aid with troubleshooting the preview function.
I've also added extensive documentation on installing ImageMagick and Ghostscript for all three platforms. I've added it to this PR as it makes reference to the functionality added here.
=> Add some checks for packages required by preview

LaTeXTools.sublime-settings
This only uses the packages `latexsym` and `mathtools`, if they are present. I don't do this for `amsmath`, because we need the `equation*` environment.
I don't now if this change is realy helpful, because standalone, preview, and amsmath are required anyway.
=> Preview: Safe use of some packages

latextools_utils/external_command.py
In some cases _command becomes a None. Also check a command has no sense: command[0] already exists, so i think it was a typo.
=> Fixed bug on opening external pdf viewer

st_preview/preview_image.py, st_preview/preview_math.py
An ugly hack to get a reference to the View object to check the syntax scope. This should allow support for previewing when using syntaxes derived from the new LaTeX syntax. Falls back to the current check if it cannot find the View object.
=> Preview: Try to use the view's scope

jumpto_anywhere.py, latex_glossary_completions.py
According to the Documentation of the glossaries latex package, \gls{}
command is used for both, the glossary entries and the acronyms.
Although the acronyms are handled by the \acr[full|short|long] command
in the plugin, these do not support that the first usage of the acronym
is written in full form and afterwards in short. Thus, \acr* commands
needs manual handling in latex, which is usually not desired.
=> Added "newacronym" in glo_filter_commands

README.markdown, st_preview/preview_image.py, st_preview/preview_math.py, st_preview/preview_utils.py, system_check.py
The intention here is to reduce the amount of configuration necessary to get equation previews working, since Ghostscript is usually installed alongside TeX.
This isn't as much help if you're also using the image preview on Windows which also requires an install of Ghostscript, but I've updated the README to include information on how to get ImageMagick to use the version of Ghostscript installed with the TeX distribution.
Finally, because this uses Ghostscript rather than ImageMagick to do the trimming, the results may be slightly different from the current version. However, it seems to do the right thing with regard to inline single-character uses and multiline equations. Admittedly, though, I haven't tried anything too complex.
Some examples:
* <img width="162" alt="equation with …
=> Preview: Use ghostscript directly for equation previews

01_reload_submodules.py, builders/pdfBuilder.py, jumpToPDF.py, latex_cite_completions.py, latextools_plugin.py, latextools_utils/internal_types.py, latextools_utils/settings.py, makePDF.py
1. As suggested by @r-stein, plugins are loaded on a non-main thread. This means that plugin loading should interfere less with start-up time.
1. Removed the automatic support for files with custom extensions. This should also marginally reduce the plugin load time.
1. Fixed the reloading code to work properly on ST2 (FillAll plugins would routinely be left out).
1. Made `get_setting()` thread-safe on ST2. This means we should be able to run more things on separate threads where it makes sense to do so.
=> Several improvements to loading plugins

latextools_utils/external_command.py
This is my actual recommendation for fixing #937. It, ultimately, does the same thing as the quick fix I made [here](https://github.com/SublimeText/LaTeXTools/issues/937#issuecomment-268834256), but also prevents similar issues from arising in other contexts, which seems to be related to not checking the stdout and / or stderr pipes.
For the most part, where external_command is used, as opposed to execute_command or check_call, etc., we don't actually care about the output. Moreover, setting stdout and stderr to PIPE seems to create issues when running certain executables, possibly because the piped stream is never read.
=> Don't set stdout to PIPE or redirect stderr in external_command

viewers/okular_viewer.py
Issue was introduced with Okular version 0.99.80+, see this tracker: https://bugs.kde.org/show_bug.cgi?id=373855
This PR fixes #989
=> Okular viewer prepend pdf path with 'file:' in forward sync, ref #989

LaTeXTools.sublime-settings, st_preview/preview_math.py
This works by adding the `dTextAlphaBits` and `dGraphicAlphaBits` settings recommended in the [Ghostscript documentation](http://www.ghostscript.com/doc/9.20/Devices.htm#File_formats). In addition, it adds a new setting `"preview_math_hires"` which, if set to `true` (default), the image is rendered at 8x the requested density and then scaled down (by Ghostscript) to the requested size. This seems to result in a clearer image. Finally, I've changed the default settings for the preview density and scale factor as image scaling in ST seems to add a small amount of distortion.
Over all, this seems to make previews crisper. For whatever reason, the current distortion seems to be more pronounced on Windows and Linux than on macOS, at least for me, and hence this has a bigger impact on Windows …
=> Preview: Provide clearer equation previews

viewers/command_viewer.py
In particular, this sets show_window to `True` when on Windows and the first part of the command is not using cmd.exe or powershell.exe. Presumably such commands will launch the viewer which will be displayed properly.
=> Fix for #986

st_preview/preview_math.py, st_preview/preview_utils.py
This should deal with #999, the underlying problem for which is that earlier versions of Ghostscript didn't support the `-dDownScaleFactor` parameter.
=> Only use preview_math_hires if using Ghostscript 9.14 or newer

01_reload_submodules.py, LaTeX.sublime-commands, LaTeXTools.sublime-settings, bibliography_plugins/newBibliography.py, bibliography_plugins/traditionalBibliography.py, delete_temp_files.py, external/frozendict.py, latex_cite_completions.py, latex_own_command_completions.py, latex_ref_completions.py, latextools_cache_listener.py, latextools_utils/analysis.py, latextools_utils/bibcache.py, latextools_utils/cache.py, latextools_utils/output_directory.py, latextools_utils/six.py, latextools_utils/system.py, latextools_utils/utils.py
TL;DR With this PR ref and cite completions use the cached analysis of the document which is asynchronously updated on save.
Essentially, I wanted to use the analysis to provide reference and citation completions, which is pretty straight-forward thanks to @r-stein's wonderful work. The problem is that in the current state, the analysis cache is only updated around once every 30 minutes, which is fine for most uses,  but becomes annoying when adding a label to a document as it may not be available immediately to be used from referencing commands.
There are a few simpler solutions to this problem:
1. Live with a 30-minute span between adding a label and LaTeXTools "seeing" it. This seems like it would get complaints from a usability perspective.
1. Ratchet down the default value for the …
=> Use analysis for Ref and Cite commands

jumpto_anywhere.py, jumpto_tex_file.py, latex_input_completions.py, latextools_utils/analysis.py, st_preview/preview_image.py
This PR adds support for the commonly used import package.
TODO list
=> Support for the import package

Default (Linux).sublime-keymap, Default (OSX).sublime-keymap, Default (Windows).sublime-keymap, LaTeXTools.sublime-settings, README.markdown, search_commands.py, toc_quickpanel.py
This adds a `only_current_file` flag to the toc quickpanel and the command search quickpanel as suggested in #942 by @jdumas.
Open discussion:
We could limit the usual ctrl+r to the file (as usual) and the ctrl+shift+r command to the whole document.
PS. If someone want to try this you can add these keybindings:
``` js
{ 
"keys": ["ctrl+r"], "command": "latex_toc_quickpanel",
"args": {"only_current_file": true},
"context": [
{"key": "selector", "operator": "equal", "operand": "text.tex"}
]
},
{ 
"keys": ["ctrl+shift+r"], "command": "latex_toc_quickpanel",
"args": {"only_current_file": false},
"context": [
{"key": "selector", "operator": "equal", "operand": "text.tex"}
]
},
```
=> Limit the TOC quickpanel to the current document

LaTeXTools (Advanced).sublime-settings, latex_fill_all.py
Per @r-stein's suggestion, the new algorithm defaults to only scanning 5 lines before (and after) the selection to determine if there is an unopened bracket that needs to be closed. This, hopefully, helps resolve the issues in #1011.
The number of lines scanned can be configured using the `smart_bracket_look_around` advanced setting, and the present behaviour of scanning the full document can be restored by using the `smart_bracket_scan_full_document` advanced setting.
I would appreciate any feedback from testing this change since it works in a couple of documents I'm currently using, but I think my documents are probably quite a bit simpler than others (I don't use too much math among other things).
=> Change the bracket completing algorithm to be less agressive

st_preview/preview_utils.py, system_check.py
Additionally, fixed the system check to NOT show a path when the executable version can't be determined.
This should address (some of) the concerns in #1038.
=> Don't use convert.exe in the system directory on Windows

README.markdown
This is a template to change the README to use prereleases in the future. In addition I created `develop` branch, where we can merge PRs before, such that we don't need to merge all PRs at once at the release day (You can just retarged PRs if you click `Edit` in the title). We should develop and issue prereleases on the `develop` branch and merge them before the release to the `master` branch.
=> Prerelease README

docs/recommended-packages.md, mkdocs.yml
This adds a "recommended packages". I think it is useful to have this section, because not every user may be super confident with all Sublime Text packages and it will be helpful for new users to have packages, which are working with LaTeX. In addition it may give some configuration ideas to all users.
=> Added "recommended packages" to the documentation

LaTeXTools.sublime-settings, st_preview/preview_math.py
This is option 2 of https://github.com/SublimeText/LaTeXTools/issues/944#issuecomment-261520926. By default it only show block environments `\begin{...}/\end{...}` and `\[...\]`
=> Added a setting to make the preview math scopes configurable

delete_temp_files.py, jumpToPDF.py, latex_input_completions.py, latextools_utils/output_directory.py, latextools_utils/settings.py, makePDF.py, system_check.py
This is intended as a fix to address the workflow outlined in #1076. I've extended it beyond `jobname` since it seem reasonable to do so to accommodate other workflow we haven't yet considered.
=> Override output_directory, aux_directory and jobname from current view

external/bibtex/lexer.py, external/bibtex/tests/lexer_tests.py, external/bibtex/tests/parser_tests.py
This should fix the underlying issue in #1115.
=> Extend parser to allow more citekey names

latex_cite_completions.py
If the cache returns an object instead of a sequence it will rerun the _find_bib_files command.
=> This temporary fixes an error with \cite{

LaTeX.sublime-commands, LaTeXTools.sublime-settings, delete_temp_files.py, latextools_utils/cache.py, st_preview/preview_image.py, st_preview/preview_math.py
This moves all cache files into a subfolder `internal`, removes the non-hidden local cache, and creates a command to delete all cache files. As far I understood the invalidate local cache command does not delete all files and this may help to resolve issues.
=> Add a command to clear the whole cache

docs/completions.md
The documentation now includes the advice from #836 that users should create a `LaTeXTools.sublime-completions` file in their `Users` folder when defining custom completions.
This provides a partial fix for #1137.
=> Add a section to the docs describing user defined completions

st_preview/preview_utils.py
With Ghostscript 9.21 installed, I got the following error 
> Traceback (most recent call last):
File "C:\Users\Tobi\AppData\Roaming\Sublime Text 3\Packages\LaTeXTools\st_preview\preview_math.py", line 559, in on_after_selection_modified_async
self.update_phantoms()
File "C:\Users\Tobi\AppData\Roaming\Sublime Text 3\Packages\LaTeXTools\st_preview\preview_math.py", line 619, in update_phantoms
self._update_phantoms()
File "C:\Users\Tobi\AppData\Roaming\Sublime Text 3\Packages\LaTeXTools\st_preview\preview_math.py", line 627, in _update_phantoms
if not ghostscript_installed():
File "C:\Users\Tobi\AppData\Roaming\Sublime Text 3\Packages\LaTeXTools\st_preview\preview_utils.py", line 220, in ghostscript_installed
return _get_gs_command() is not None
File "C:\Users\Tobi\AppData\Roaming\Sublime …
=> Fix conversation problem when using preview

st_preview/preview_utils.py
I got the following message when Ghostscript was not installed
> Traceback (most recent call last):
File "C:\Users\Tobi\AppData\Roaming\Sublime Text 3\Packages\LaTeXTools\st_preview\preview_utils.py", line 99, in _update_gs_version
raw_version = check_output([_GS_COMMAND, '-version'])
File "C:\Users\Tobi\AppData\Roaming\Sublime Text 3\Packages\LaTeXTools\latextools_utils\external_command.py", line 348, in check_output
show_window=show_window
File "C:\Users\Tobi\AppData\Roaming\Sublime Text 3\Packages\LaTeXTools\latextools_utils\external_command.py", line 268, in execute_command
show_window=show_window
File "C:\Users\Tobi\AppData\Roaming\Sublime Text 3\Packages\LaTeXTools\latextools_utils\external_command.py", line 181, in external_command
if not os.path.isabs(command[0]):
File …
=> Output better error message if ghostscript was not found

latex_glossary_completions.py, latextools_utils/pgf.py
This improves the description in the glossary completion overlay by adding a second line, which contains the glossary name and description (as it is already done in the acr completion, but can only be added with the new analysis for nested commands).
=> Improve glossary completions

01_reload_submodules.py, Default.sublime-keymap, latex_fill_all.py, latextools_utils/input_quickpanel.py
This quickpanel is by default used by the fill-all helper. You can select the entry with `enter` and insert the text with `tab`.
This resolves #1051
=> Added a quickpanel, which is able to input characters

Default (Linux).sublime-keymap, Default (OSX).sublime-keymap, Default (Windows).sublime-keymap, change_environment.py
Builds on https://github.com/SublimeText/LaTeXTools/pull/585 by @r-stein to add a command for toggling the starred version of a surrounding environment with keybinding `C-l,C-*`.  This is useful for enabling/disabling numbering of math environments such as `equation` and `align`.  The implementation reuses existing logic in `latex_change_environment` for detecting environment regions so it should work with nested environments and multiple cursors.
Demo
=> Add command for toggling starred version of surrounding environment

parseTeXlog.py
fix parsing for "Incomplete \if...; all text was ignored after line"
fix https://github.com/SublimeText/LaTeXTools/issues/1199 and https://github.com/SublimeText/LaTeXTools/issues/1205
=> fix parsing for "Incomplete \if...; all text was ignored after line"

latextools_utils/cache.py
Basically, this re-implements `_invalid_object` (the marker object used to mark an invalidated cache entry) in a way that will survive LaTeXTools being reloaded. This is the root cause of a number of issues with bibliography entries returned from the cache being incorrect. While it will work for future caches, current caches will need to be deleted to see any sort of effect.
=> Fix cache returning unidentified `object()`

parseTeXlog.py
The unfinished line detection code was never triggering, causing `(Log parsing issues. Disregard unless something else is wrong.)` errors. 
For an MWE, try compiling this on Windows:
```
\documentclass{article}
\usepackage{pgfcore}
\begin{document}
If run on Windows, the log file will now contain several lines (e.g. l.150, l.160) that have only a single quote mark. Try searching for 
\verb¬^[^\n"]*"[^\n"]*$¬ to find them. 
\end{document}
```
=> Fix bug where unfinished lines were not being detected

builders/basicBuilder.py
Makes the regex for the basic builder more permissive. Should fix #1298.
=> Fix for 1298

Default.sublime-keymap, Delete Left Right Bracket 1 2.sublime-macro, Delete Left Right Bracket 1.sublime-macro, Delete Left Right Bracket 2 1.sublime-macro, Delete Left Right Bracket 2.sublime-macro, Delete Left Right Twice.sublime-macro, Delete Left Twice.sublime-macro
This has been suggested by @Romeoly in #1193, by @skulumani in #917, and by @FichteFoll in #963.
It currently does:
(&#124; is the caret position)
insert | get
--- | ---
`\{` | `\{`&#124;`\}`
`\[` | `\[`&#124;`\]`
`\(` | `\(`&#124;`\)`
`\left(` | `\left(`&#124;`\right)`
It also changes the backpace behavior (same for parens and braces):
before pressing | after pressing
--- | ---
`\[`&#124;`\]` | &#124;
`\[\]`&#124; | `\[`&#124;
`\[`&#124; | &#124;
`\left(`&#124;`\right)` | &#124;
I am open to discussion for more worthy additions.
=> Auto-pair escaped braces, brackets, and parens

latextools_utils/sublime_utils.py
A reference to `set_async_timeout` should be `set_timeout_async`. I only found this typo in `latextools_utils/sublime_utils.py`. For more information see these:
- https://github.com/SublimeTextIssues/Core/issues/825
- https://www.sublimetext.com/docs/3/api_reference.html
All other uses of the timeout are correct as far as I can tell.
=> Fixed a reference to set_async_timeout (should be set_timeout_async).

Default (Linux).sublime-keymap
The environment was misspelled, implying a non functional keybinding for subscreipting
=> typo fix for subscript snippet

system_check.py
fix byte to string decoding error  when checking version of `ImageMagick` missing or available.
=> Fix an encoding issue when looking for ImageMagick

makePDF.py
=> copy_on_build should not fail on nonexistent extensions

docs/features.md, docs/settings.md, latextools_utils/settings.py, latextools_utils/tex_directives.py, toggle_settings.py
To avoid collisions with other packages preview view and project settings with `latextools.`
=> Prefix view settings with `latextools.`

latex_cwl_completions.py
=> blackslash is now handled correctly in sublime text 4

latex_installed_packages.py
Addressing issue https://github.com/SublimeText/LaTeXTools/issues/1425
```LatexTools: Build cache of LaTex packages``` command might fail due to no bst installed. There would be KeyError for 'bst'. Thus, it would be nice if we could use the get method to avoid this error.
=> Bug fix for no pkg cache

st_preview/preview_math.py
The previous formulation required character 0 of the document to be consider LaTeX. This change allows the preview to apply to any document which contains embedded latex scopes.
An example can be seen in https://github.com/sublimehq/Packages/pull/2145#discussion_r338840922
=> Allow use of math preview in embedded latex scopes

jumpto_tex_file.py
Allows `\input{"../my folder/my file.tex"}` to be read as `\input{../my folder/my file.tex}`.  The former is necessary to have filenames with spaces to be typeset by LaTeX, but without this change, the command _jumpto_tex_file ends up creating a folder called `"..` (that's doublequote then dot dot) in the home folder.
=> strip doublequotes from filename in _jumpto_tex_file

Default (Linux).sublime-keymap, Default (OSX).sublime-keymap, Default (Windows).sublime-keymap, LaTeXTools.sublime-settings, docs/settings.md
Resolves #1618 
This commit properly handles escape sequences in front of opening brackets, in order to avoid false-positive auto-pairing in unwanted situations.
=> Improve auto-pairing of brackets

plugins/viewer/skim_viewer.py
**Summary**  
Opening PDFs with the Skim viewer crashed with:
```vbnet
TypeError: expected string or bytes-like object
at shlex.quote(...)
at latextools/utils/external_command.py
```
Root cause: `plugins/viewer/skim_viewer.py` passed a `pathlib.Path` (`script_file`) in the `command` list to `external_command()`. That function later quotes each arg with `shlex.quote()`, which requires `str`/`bytes`.
**Change**  
Cast `script_file` to `str` when building the command:
```diff
- command = ["/bin/sh", script_file, "-r"]
+ command = ["/bin/sh", str(script_file), "-r"]
```
=> Fix Skim viewer crash by casting `script_file` (PosixPath) → `str`

Default (Linux).sublime-keymap, Default (OSX).sublime-keymap, Default (Windows).sublime-keymap
Fixes #1655
This commit adds a key binding to actively cancel auto completions, if escaped backslash `\\` is typed, which indicates a manual "newline".
It prevents unwanted completions from being inserted, if enter is pressed.
Note: A key binding is used as `cancelCompletion` rule doesn't provide reliable
behavior, especially if `\\` is typed in the middle of a sentence.
=> Cancel completions if escaped backslash is typed

Default.sublime-commands, LaTeXTools.sublime-settings, latextools/make_pdf.py
This PR makes three small but related improvements around the LaTeXTools build panel:
* **Expose "Show build panel" in the Command Palette**
* Adds a new command palette entry:
```
makefileCopy codeLaTeXTools: Show build panel
```
* This provides a discoverable way for users to reopen the build panel manually (useful when `"hide_build_panel"` is set to `"always"` or `"never"`).
* **Clarify and correct documentation of `hide_build_panel`**
* The previous comments in `LaTeXTools.sublime-settings` were inconsistent:
* The code fallback was `"no_warnings"`.
* The defaults file set `"no_badboxes"`.
* The comments claimed `"never"` was the default.
* The docs are now clearer, consistent, and explicitly state the true default.
* **Align code fallback with shipped defaults**
* In `make_pdf.py`, …
=> Improve consistency and usability of build panel handling

LaTeXTools.sublime-settings, docs/settings.md, latextools/make_pdf.py, plugins/builder/basic_builder.py, plugins/builder/pdf_builder.py, plugins/builder/traditional_builder.py
Resolve #1654
Resolve #1659
This PR modifies possible values of `"open_pdf_on_build"` setting to:
* `"never"`: PDF viewer is only launched if explicitly requested using `C-l,v` or `C-l,j`.
* `"success"`: PDF is opened only, if build reports success.
* `"always"`: PDF file is opened, even if build reported an error and PDF is most likely incomplete.
=> Add option to open incomplete PDF after build

LaTeXTools Build Output.sublime-syntax, latextools/make_pdf.py, tests/syntax/syntax_test_build.log
Resolves #374
If build succeeds, output duration as default build system.
```
[Finished in 20.4s]
```
=> Display compile time after build

snippets/Wrap in command.sublime-snippet, snippets/Wrap in environment.sublime-snippet
Resolves #1016
This PR automatically stripps a single newline from selection, when wrapping it into an environment or command.
As a result outcome is the same regardless a line is selected with or without trailing newline character - in other words: the caret is at the eol of selected line or bol of line after.
=> Wrap selection in environment with newline stripped

latextools/latex_cite_completions.py, latextools/utils/analysis.py
Resolves #998
This commit introduces a naive hacky way to remove `\string` from path strings. Fixes bibliography lookup in case path contains `\string` tokens.
Note: 
1. It probably requires more than that to make sure path strings are correctly decoded and converted to valid os paths.
2. Other modules like `\graphicsinput` may also be affected.
=> LaTeX decode bibliography paths

Default (Linux).sublime-keymap, Default (OSX).sublime-keymap, Default (Windows).sublime-keymap
Resolves #1043
This commit adds separate key bindings for wrapping words or selections into emphasis tags. If nothing is selected, expand selection to word boundaries before inserting emphasis snippet.
=> Wrap word under caret into bold/emphasis/underline

Default (Linux).sublime-keymap, Default (OSX).sublime-keymap, Default (Windows).sublime-keymap
Fixes #1391
Implement unique auto-pair key bindings for latex scope, to prevent auto-pairing after `\` as \' and \" are used to denote umlaut typesetting (e.g.: \"o -> ö).
=> Fix quotation auto-pairing

LaTeXTools.sublime-settings, latextools/preview/__init__.py
Resolves #1362
Resolves https://github.com/REditorSupport/sublime-ide-r/issues/4
This commit enables math preview phantoms in Markdown syntax.
Primarily targets R-Markdown, but also applies to ordinary Markdown, which also uses LaTeX style equations.
=> Fix math preview in Markdown syntaxes
