SublimeText/LaTeXTools

kpsewhich.py

Pull request to fix #498. Will add some details there.

Bugfix: Make kpsewhich work on OS X

---

latex_cwl_completions.py

This resolves https://github.com/SublimeText/LaTeXTools/issues/640.
Since `\` is in the `auto_complete_triggers` the auto-completion also appeared if it was escaped. This PR checks whether it is escaped and optionally hides the auto-completion. If the user has not configured the auto-completion to popup in the scope, then the auto-completion is not hidden.
It also removed the cwl entries from the auto-completion if the leading backlash is escaped.

Hide (cwl) auto-completion popup if the leading backslash is escaped

---

latex_input_completions.py

Simply added the \includesvg regex and svg_filter to latex_input_completions.py

Adding includesvg to input completion

---

latex_cite_completions.py

\addbibresource, \addglobalbib, \addsectionbib and \begin{refsection}
Look for bibliography resources even if those commands use optional arguments.

add support for more biblatex commands

---

00_reload_submodules.py
LaTeXTools.sublime-settings
README.markdown
latextools_utils/system.py
viewers/zathura.py

Adds support for Zathura. This supercedes #468.

Add a viewer for Zathura

---

viewers/zathura_viewer.py

Use --synctex-editor-command when Zathura run from forward_sync

---

toggle_show.py

This uses a panel in the `toggle_show` (`C-l, t, ?`) instead of a status message.
This has the advantage that it is better readable for the user and can directly toggled. In addition it uses the new `get_setting` function.
Demo:

Use a panel in `toggle_show` instead of a status message

---

LaTeXTools.sublime-settings
README.markdown
makePDF.py

See https://forum.sublimetext.com/t/latextools-panel-color/21653/7.
I also reorganised some of the settings, etc. to group related settings together.

Add an option to control whether or not to highlight the build panel

---

latex_cite_completions.py

Add citation completions for \bibentry

---

evince/evince_forward_search

Switch from using time.time() -> 0

---

evince/evince_backward_search
evince/evince_forward_search

Fix issues with Evince URL encoding

---

Default (Linux).sublime-keymap
Default (OSX).sublime-keymap
Default (Windows).sublime-keymap
LaTeXTools.sublime-settings
README.markdown
jumpto_anywhere.py
jumpto_tex_file.py
latex_glossary_completions.py
latextools_utils/analysis.py
latextools_utils/cache.py
toggle_show.py

This adds support for the glossary package as requested in https://github.com/SublimeText/LaTeXTools/issues/676 to FillAllHelper *autocompletion* and jump-to-anywhere *jump to entry definitions*.

Support for the glossary package

---

latex_cwl_completions.py

Avoid cwl completion from inserting \ if it is already present

---

makePDF.py

Ensure copy_on_build is honoured if set

---

st_preview/preview_math.py

This adds an additional *(Disable)* button to disable the math preview. Since we don't change the LaTeXTools settings, it gives instructions how to disable it and disables the preview until ST is restarted.

Added a (Disable) button to the math preview

---

st_preview/preview_image.py

Basically adds ideas from https://bugs.python.org/issue16512#msg198034 and http://stackoverflow.com/a/39778771, which adds support for some jpeg files not supported by the current `get_image_size()` implementation.

Preview: Add support for more JPEG files

---

latex_cwl_completions.py

Precomputes some values and runs fewer expensive checks. This is intended to address #933.

Small improvements to cwl completions

---

change_environment.py

Updates the regex in change_environment.py

---

builders/traditionalBuilder.py

Remove quotes from string passed to latexmk

---

README.markdown

- maintain a TeX distribution is a time-consuming task
+ maintaining a TeX distribution is a time-consuming task

fixed typo in README

---

latextools_utils/tex_directives.py

%!TEX root directive will now override settings regardless of which file is active. This should resolve #1032.

%!TEX directives overwrites settings

---

LaTeX.sublime-commands
open_detexify.py

This adds a command to open the detexify web page. This is useful identify the command names by drawing symbols.
http://detexify.kirelabs.org/classify.html

Open Detexify command

---

parseTeXlog.py

These are @msiniscalchi patches from #1098

Improve badbox log parsing code

---

latextools_utils/analysis.py

Don't stop the analysis at \end{document}

---

dependencies.json
latextools_utils/analysis.py

The analysis now uses the regex module instead of the re module to also support nested commands, i.e. \commanda{\commandb{test]}} is now handled correctly.

The analysis now support nested commands

---

latextools_utils/analysis.py

If the analysis starts in the subfiles it will automatically scan the preamble of the main document.
Resolves #1143

Improved support for subfiles in the analysis

---

LaTeXTools.sublime-settings
latex_cite_completions.py

Added a setting to define an additional bib file in the settings

---

makePDF.py

This enables a link to direct open the .log file from the console.

Adding a line with the current .log file in the console output.

---

LaTeXTools.sublime-settings
delete_temp_files.py

Add an optional check when deleting temp files

---

vendor/bibtex/names.py
vendor/bibtex/tests/names_tests.py

Add support for key-value author in bibliography

---

Beamer.sublime-completions

They are provided by cwl completions already, so just cause duplicates.

Remove static beamer completions

---

latextools/jumpto_anywhere.py
latextools/utils/analysis.py
latextools/utils/utils.py

resolves https://forum.sublimetext.com/t/issue-with-latextools-jumpto-anywhere/76061

Fix goto anywhere

---

Default (Linux).sublime-keymap
Default (OSX).sublime-keymap
Default (Windows).sublime-keymap

Add binding to wrap selected text in pipes

---

Default (Linux).sublime-keymap
Default (OSX).sublime-keymap
Default (Windows).sublime-keymap

Fix auto-pairing augmenting cite/ref autofill

---

latextools/jumpto_tex_file.py
latextools/latex_input_completions.py

Resolves #1625
This PR adds support for `\includegraphics<N>{...}` completions.

Fix beamer includegraphics

---

latextools/utils/analysis.py

1. skip loading empty imports
2. fix parsing input commands with `args2`

Fix `\input{}` analysis

---

latextools/latex_ref_completions.py

Add \zref completions
